version: "2"

services:

  mongodb:
    container_name: mongo-compose
    image: mongo:latest
    ports:
      - "27017:27017"
  neo4j:
    container_name: neo4j-compose
    image: neo4j:3.0
    ports:
     - "7474:7474"
    environment:
    - NEO4J_AUTH=neo4j/12345q
